### ISSUE TITLE
Totally broken?

### ISSUE THREAD

**Issue by nostahl** [frappe/drive#357]
tested docker, tested bench install app , tested frappe cloud and its all broken Tons of errors in console log  nothing working.. what happened?

**Comment by safwansamsudeen** [comment]
Hey @nostahl,

I can't reproduce - my instances are working fine. Could you give more detail?

**Comment by nostahl** [comment]
<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/46f35335-e665-4715-b345-c187687114a6" /> no navbar just a left sidebar. it looks totally broken on a fresh install on frappe cloud's automated installer.

**Comment by safwansamsudeen** [comment]
Fixed, thanks! If you could confirm, I'll close the issue.

**Comment by nostahl** [comment]
<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/e5802694-c315-4cbd-bf82-9a92d63d52d9" /> I see the navbar now but still all sorts of console log errors. tried making a test folder and document but after refreshing the page the test folder appeared. and nothing happens when I click to create new document

**Comment by safwansamsudeen** [comment]
For me, document creation works fine (the bug in folder creation will be fixed soon).

This might be related to another issue - please update your Drive app to the latest instance (pushed now). If it still doesn't work, open a separate issue.

**Comment by nostahl** [comment]
@safwansamsudeen what is the deal with the invalid url for WebSocket? I just updated and it still shows that in console log
